version: "3.8"

services:
  # ---------- ZOOKEEPER ----------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - football-net

  # ---------- KAFKA ----------
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - football-net

  # ---------- KAFKA UI ----------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: football-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - football-net

  # ---------- POSTGRES ----------
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: football
      POSTGRES_USER: football_user
      POSTGRES_PASSWORD: football_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - football-net

  # ---------- SPARK MASTER ----------
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "8088:8088"
      - "7077:7077"
    networks:
      - football-net

  # ---------- SPARK WORKER ----------
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    environment:
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
    networks:
      - football-net

  # ---------- SPARK SUBMIT ----------
  spark-submit:
    build: .
    image: football-spark:3.5
    container_name: spark-submit
    depends_on:
      - spark-master
      - kafka
      - postgres
    volumes:
      - ./spark:/opt/spark/work-dir
    restart: unless-stopped
    entrypoint: >
      /bin/bash -c "sleep 20 &&
      /opt/spark/bin/spark-submit
      --master spark://spark-master:7077
      --conf spark.driver.extraJavaOptions='-Divy.cache.dir=/tmp -Divy.home=/tmp'
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.postgresql:postgresql:42.7.1
      /opt/spark/work-dir/spark_processor.py"
    networks:
      - football-net


networks:
  football-net:
    driver: bridge

volumes:
  pgdata:
